adding quotes

diff --git a/script/class-setup b/script/class-setup
--- a/script/class-setup
+++ b/script/class-setup
@@ -39,6 +39,7 @@ function ValidateJQ ()
   ##############################
   if [ $ERROR_CODE -ne 0 ]; then
     echo "ERROR! Failed to find [jq] installed on system!"
+    echo "ERROR:[$VALIDATE_JQ_CMD]"
     echo "Please install to system before next run!"
     echo "grab it from https://stedolan.github.io/jq/download/"
     exit 1
@@ -70,7 +71,7 @@ function TokenOwner ()
   ##############################
   # See if we have token owner #
   ##############################
-  if [ -z ${CLIENT_TOKEN_OWNER+x} ]
+  if [ -z "${CLIENT_TOKEN_OWNER+x}" ]
     then
       echo "It looks like we'll need to add the CLIENT_TOKEN_OWNER var"
       echo "to your ~/.trainingclientrc. Please type the github username"
@@ -79,8 +80,8 @@ function TokenOwner ()
       #####################
       # Read in the input #
       #####################
-      read NEW_NAME
-      echo "export CLIENT_TOKEN_OWNER='$NEW_NAME'" >> $HOME/.trainingclientrc
+      read -r NEW_NAME
+      echo "export CLIENT_TOKEN_OWNER='$NEW_NAME'" >> "$HOME/.trainingclientrc"
     else
       echo "CLIENT_TOKEN_OWNER = $CLIENT_TOKEN_OWNER."
   fi
@@ -93,7 +94,7 @@ function DemoPAT ()
   ##############################
   # See if we have teacher pat #
   ##############################
-  if [ -z ${CLIENT_PAT+x} ]; then
+  if [ -z "${CLIENT_PAT+x}" ]; then
     echo "It looks like we need to add the"
     echo "CLIENT_PAT var to your ~/.trainingclientrc."
     echo "Please generate a Personal Access token on the"
@@ -102,8 +103,8 @@ function DemoPAT ()
     #####################
     # Read in the token #
     #####################
-    read -s NEW_TOKEN
-    echo "export CLIENT_PAT='$NEW_TOKEN'" >> $HOME/.trainingclientrc
+    read -r -s NEW_TOKEN
+    echo "export CLIENT_PAT='$NEW_TOKEN'" >> "$HOME/.trainingclientrc"
   else
     echo "CLIENT_PAT is set!"
   fi
@@ -117,15 +118,24 @@ function InstanceURL ()
   ###############################
   # See if we have instance url #
   ###############################
-  if [ -z ${CLIENT_URL+x} ]; then
+  if [ -z "${CLIENT_URL+x}" ]; then
     echo "It looks like you need to add the"
     echo "CLIENT_URL var to your ~/.trainingclientrc. Please type the"
     echo "root endpoint for your github instance."
     echo "For example: api.github.com OR github.mycompany.com/api/v3"
-    read NEW_URL
+    ##################
+    # Read the input #
+    ##################
+    read -r NEW_URL
     echo "Checking if '$NEW_URL' is accessible... (this may take several minutes)"
-    curl -s $NEW_URL >> log.out 2>&1
-    if [ 0 -eq $? ]
+    curl -s "$NEW_URL" >> log.out 2>&1
+
+    #######################
+    # Load the error code #
+    #######################
+    ERROR_CODE=$?
+
+    if [ $ERROR_CODE -eq 0 ]
       then
         echo "API endpoint verified"
       else
@@ -137,19 +147,19 @@ function InstanceURL ()
     if [[ $(curl -s -u "$NEW_NAME:$NEW_TOKEN" "https://$NEW_URL/" | jq .message) = null ]]
       then
         echo "API endpoint + authentication verified"
-        echo "export CLIENT_URL='$NEW_URL'" >> $HOME/.trainingclientrc
+        echo "export CLIENT_URL='$NEW_URL'" >> "$HOME/.trainingclientrc"
       else
         echo "Can't make an authenticated request to the API."
         exit 1
     fi
     if echo "$NEW_URL" | grep -iq "\<api.github.com\>" ;
       then
-        echo "export ROOT_URL='github.com'" >> $HOME/.trainingclientrc
+        echo "export ROOT_URL='github.com'" >> "$HOME/.trainingclientrc"
       else
         #strip the API part
         strippedURL=$(echo "$NEW_URL" | sed -E 's/\/api\/v3//')
-        echo "export ROOT_URL='$strippedURL'" >> $HOME/.trainingclientrc
-        echo "export CLIENT_URL='$CLIENT_URL'" >> $HOME/.trainingclientrc
+        echo "export ROOT_URL='$strippedURL'" >> "$HOME/.trainingclientrc"
+        echo "export CLIENT_URL='$CLIENT_URL'" >> "$HOME/.trainingclientrc"
     fi
   else
     echo "CLIENT_URL = $INSTANCE_URL"
@@ -165,18 +175,21 @@ function ClassOrg ()
   ##########################
   # See if we have the Org #
   ##########################
-  if [ -z ${CLIENT_CLASS_ORG+x} ]
+  if [ -z "${CLIENT_CLASS_ORG+x}" ]
     then
       echo "It looks like you need to add the CLIENT_CLASS_ORG var"
       echo "to your ~/.trainingclientrc. Please type the organization name"
       echo "used for github training on your instance."
       echo "For example: githubschool"
-      read NEW_ORG
+      ##################
+      # Read the input #
+      ##################
+      read -r NEW_ORG
       echo "Checking if $NEW_ORG is accessible via the API..."
-      if [[ $(curl -s -u "$NEW_NAME:$NEW_TOKEN" https://$NEW_URL/orgs/$NEW_ORG | jq .message) = null ]]
+      if [[ $(curl -s -u "$NEW_NAME:$NEW_TOKEN" "https://$NEW_URL/orgs/$NEW_ORG" | jq .message) = null ]]
             then
           echo "That organization was verified."
-          echo "export CLIENT_CLASS_ORG='$NEW_ORG'" >> $HOME/.trainingclientrc
+          echo "export CLIENT_CLASS_ORG='$NEW_ORG'" >> "$HOME/.trainingclientrc"
         else
           echo "Can't access the organization via the API."
           exit 1
@@ -193,14 +206,17 @@ function SurveyToken ()
   ###################################
   # See if we have the survey token #
   ###################################
-  if [ -z ${CLIENT_SURVEY_TOKEN+x} ]
+  if [ -z "${CLIENT_SURVEY_TOKEN+x}" ]
     then
       echo "The scripts use the SurveyGizmo API to auto-generate"
       echo "the post-class survey. You will need to add the API"
       echo "Key found in SurveyGizmo (Log In -> Account -> Integrations -> API Key)"
       echo " to your ~/.trainingclientrc. Please paste the API Key below:"
-      read SURVEY_TOKEN
-      echo "export CLIENT_SURVEY_TOKEN='$SURVEY_TOKEN'" >> $HOME/.trainingclientrc
+      ##################
+      # Read the input #
+      ##################
+      read -r SURVEY_TOKEN
+      echo "export CLIENT_SURVEY_TOKEN='$SURVEY_TOKEN'" >> "$HOME/.trainingclientrc"
     else
       echo "CLIENT_SURVEY_TOKEN is set!"
   fi
@@ -213,14 +229,17 @@ function SurveySecret ()
   ####################################
   # See if we have the survey secret #
   ####################################
-  if [ -z ${CLIENT_SURVEY_SECRET+x} ]
+  if [ -z "${CLIENT_SURVEY_SECRET+x}" ]
     then
       echo "The SurveyGizmo API also requires a secret key."
       echo "You will need to add the api"
       echo "secret key generated by SurveyGizmo to your ~/.trainingclientrc."
       echo "Please paste it below:"
-      read SURVEY_SECRET
-      echo "export CLIENT_SURVEY_SECRET='$SURVEY_SECRET'" >> $HOME/.trainingclientrc
+      ##################
+      # Read the input #
+      ##################
+      read -r SURVEY_SECRET
+      echo "export CLIENT_SURVEY_SECRET='$SURVEY_SECRET'" >> "$HOME/.trainingclientrc"
     else
       echo "CLIENT_SURVEY_SECRET is set!"
   fi
@@ -233,13 +252,16 @@ function SurveyCampaign ()
   #####################################
   # See if we have the survey campain #
   #####################################
-  if [ -z ${CLIENT_SURVEY_CAMPAIGN+x} ]
+  if [ -z "${CLIENT_SURVEY_CAMPAIGN+x}" ]
     then
       echo "The survey created in SurveyGizmo is assigned a unique"
       echo "campaign number. Go ahead and add it to your ~/.trainingclientrc."
       echo "By pasting it below:"
-      read SURVEY_CAMPAIGN
-      echo "export CLIENT_SURVEY_CAMPAIGN='$SURVEY_CAMPAIGN'" >> $HOME/.trainingclientrc
+      ##################
+      # Read the input #
+      ##################
+      read -r SURVEY_CAMPAIGN
+      echo "export CLIENT_SURVEY_CAMPAIGN='$SURVEY_CAMPAIGN'" >> "$HOME/.trainingclientrc"
     else
       echo "CLIENT_SURVEY_CAMPAIGN = $SURVEY_CAMPAIGN"
   fi
@@ -252,13 +274,16 @@ function ApptURL ()
   ###############################
   # See if we have the appt url #
   ###############################
-  if [ -z ${CLIENT_APPT_URL+x} ]
+  if [ -z "${CLIENT_APPT_URL+x}" ]
     then
       echo "If you will offer 1:1 appointments with your students,"
       echo "you will need to add the booking URL to your ~/.trainingclientrc"
       echo "by pasting it below:"
-      read APPT_URL
-      echo "export CLIENT_APPT_URL='$APPT_URL'" >> $HOME/.trainingclientrc
+      ##################
+      # Read the input #
+      ##################
+      read -r APPT_URL
+      echo "export CLIENT_APPT_URL='$APPT_URL'" >> "$HOME/.trainingclientrc"
     else
       echo "CLIENT_APPT_URL = $APPT_URL"
   fi
@@ -273,10 +298,13 @@ function ShellCheck ()
   #########################
   echo "What kind of shell are you using?"
   echo "acceptable options: bash, zsh"
-  read SHELL
+  ##################
+  # Read the input #
+  ##################
+  read -r SHELL
   echo "Adding to your .${SHELL}rc..."
-  echo "\n# added by github/training-manual class setup" >> $HOME/.${SHELL}rc
-  echo "test -f \"$HOME/.trainingclientrc\" && source \"$HOME/.trainingclientrc\"" >> $HOME/.${SHELL}rc
+  echo "\n# added by github/training-manual class setup" >> "$HOME/.${SHELL}rc"
+  echo "test -f \"$HOME/.trainingclientrc\" && source \"$HOME/.trainingclientrc\"" >> "$HOME/.${SHELL}rc"
 
   echo "ATTENTION: You must restart your open terminal sessions"
   echo "for changes to take effect."
