Replace student Pages URL with template Pages URL

diff --git a/script/create-game-repos b/script/create-game-repos
--- a/script/create-game-repos
+++ b/script/create-game-repos
@@ -9,6 +9,7 @@
 # saved to your ENV variables in order to use this script #
 ###########################################################
 COLLAB_REPO=$1
+TEMPLATE_REPO="github-games"
 
 ################################################################################
 ########################## Functions Below #####################################
@@ -32,28 +33,30 @@ function GetNames() {
   # Check the root url #
   ######################
   if [[ "$ROOT_URL" == "github.com" ]]; then
-    ##############
-    # Clone repo #
-    ##############
-    git clone --bare "https://github.com/githubtraining/github-games" game-template >> log.out 2>&1
+    TEMPLATE_REPO_URL="https://github.com/githubtraining/$TEMPLATE_REPO"
   else
-    ##############
-    # Clone repo #
-    ##############
-    git clone --bare "https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/github-games" game-template >> log.out 2>&1
+    TEMPLATE_REPO_URL="https://$TOKEN_OWNER:$TEACHER_PAT@$ROOT_URL/$CLASS_ORG/$TEMPLATE_REPO"
+  fi
 
-    #######################
-    # Load the error code #
-    #######################
-    ERROR_CODE=$?
+  ##############
+  # Clone repo #
+  ##############
+  git clone --bare "$TEMPLATE_REPO_URL" game-template >> log.out 2>&1
 
-    #########################
-    # Check the shell error #
-    #########################
-    if [ $ERROR_CODE -ne 0 ]; then
-      echo "!!! Couldn't clone template repo at all. Please grab a copy from https://github.com/githubtraining/github-games and upload it to your GHE instance."
-      exit 1
+  #######################
+  # Load the error code #
+  #######################
+  ERROR_CODE=$?
+
+  #########################
+  # Check the shell error #
+  #########################
+  if [ $ERROR_CODE -ne 0 ]; then
+    echo "!!! Couldn't clone template repo."
+    if [[ "$ROOT_URL" != "github.com" ]]; then
+      echo "Please grab a copy from https://github.com/githubtraining/$TEMPLATE_REPO and upload it to your GHE instance."
     fi
+    exit 1
   fi
 
   ###########
@@ -99,8 +102,10 @@ function CreateRepo() {
   # Pull in the vars #
   ####################
   STUDENT=$1
-  STUDENT_REPO="github-games-"$STUDENT
-  PAGES_URL=''
+  STUDENT_REPO="$TEMPLATE_REPO-"$STUDENT
+  STUDENT_PAGES_URL=''
+  TEMPLATE_PAGES_URL=''
+
   echo "Time to create $STUDENT_REPO for $STUDENT"
   #create a repo named github-games-$STUDENT in $CLASS_ORG org
   echo "Create server-side location for fresh $CLASS_ORG/$STUDENT_REPO repo..."
@@ -109,17 +114,19 @@ function CreateRepo() {
   # Check the root #
   ##################
   if [[ "$ROOT_URL" == "github.com" ]]; then
-    echo "Creating on GITHUB"
-    PAGES_URL="https://${CLASS_ORG}.github.io/${STUDENT_REPO}/"
+    echo "Creating on GitHub"
+    STUDENT_PAGES_URL="https://${CLASS_ORG}.github.io/${STUDENT_REPO}/"
+    TEMPLATE_PAGES_URL="https://${CLASS_ORG}.github.io/${STUDENT_REPO}/"
   else
-    echo "Creating on Enterprise"
-    PAGES_URL="https://${ROOT_URL}/pages/${CLASS_ORG}/${STUDENT_REPO}/"
+    echo "Creating on GitHub Enterprise Server"
+    STUDENT_PAGES_URL="https://${ROOT_URL}/pages/${CLASS_ORG}/${STUDENT_REPO}/"
+    TEMPLATE_PAGES_URL="https://${ROOT_URL}/pages/${CLASS_ORG}/${STUDENT_REPO}/"
   fi
 
   #############
   # Create it #
   #############
-  curl -s -i -u "${TOKEN_OWNER}:${TEACHER_PAT}" -d "{ \"name\": \"${STUDENT_REPO}\", \"description\": \"A fun way to learn about git troubleshooting.\", \"homepage\": \"${PAGES_URL}\", \"private\": false, \"has_issues\": true, \"has_wiki\": true, \"has_downloads\": true}" -X POST "https://${INSTANCE_URL}/orgs/${CLASS_ORG}/repos" >> log.out 2>&1
+  curl -s -i -u "${TOKEN_OWNER}:${TEACHER_PAT}" -d "{ \"name\": \"${STUDENT_REPO}\", \"description\": \"A fun way to learn about git troubleshooting.\", \"homepage\": \"${TEMPLATE_PAGES_URL}\", \"private\": false, \"has_issues\": true, \"has_wiki\": true, \"has_downloads\": true}" -X POST "https://${INSTANCE_URL}/orgs/${CLASS_ORG}/repos" >> log.out 2>&1
 
   ##################
   # Wait to finish #
@@ -147,8 +154,8 @@ function CreateRepo() {
   ##############################
   # create issues for problems #
   ##############################
-  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"Game broken\", \"body\": \"When attempting to access this at ${PAGES_URL}, I am getting a 404. This could be caused by a couple things:\n\n - GitHub pages needs to be enabled on master. You can fix this in the repository settings.\n- the index.html file is incorrectly named inde.html. We will fix this together in class.\n\n Can you please fix the first bullet @$STUDENT?\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/issues" >> log.out 2>&1
-  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"URL in README broken\", \"body\": \"The URL in the README is pointing to $CLASS_ORG's copy of the game instead of yours. \n\n Please fix it so that it points to your copy of the game at ${PAGES_URL}\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/issues" >> log.out 2>&1
+  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"Game broken\", \"body\": \"When attempting to access this at ${STUDENT_PAGES_URL}, I am getting a 404. This could be caused by a couple things:\n\n - GitHub pages needs to be enabled on master. You can fix this in the repository settings.\n- the index.html file is incorrectly named inde.html. We will fix this together in class.\n\n Can you please fix the first bullet @$STUDENT?\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/issues" >> log.out 2>&1
+  curl -s -i -u "$TOKEN_OWNER:$TEACHER_PAT" -d "{ \"title\": \"The URL in the repository description and README are pointing to ${CLASS_ORG}'s copy of the game instead of yours. \n\n Please fix both so they point to your copy of the game at ${STUDENT_PAGES_URL}\"}" -X POST "https://$INSTANCE_URL/repos/$CLASS_ORG/$STUDENT_REPO/issues" >> log.out 2>&1
 
   #############################
   # assign issues to $STUDENT #
