more cleanup

diff --git a/script/generate-pdf b/script/generate-pdf
--- a/script/generate-pdf
+++ b/script/generate-pdf
@@ -1,8 +1,86 @@
+#!/bin/bash
+################################################################################
+############################## Generate PDF ####################################
+################################################################################
+
+##########
+# Header #
+##########
 echo "Creating a PDF... if this fails check out the documentation at: https://toolchain.gitbook.com/ebook.html"
-  
+
+###############
+# NPM Install #
+###############
 npm install -g gitbook-cli
+
+#######################
+# Load the error code #
+#######################
+ERROR_CODE=$?
+
+##############################
+# Check the shell for errors #
+##############################
+if [ $ERROR_CODE -ne 0 ]; then
+  echo "ERROR! Failed to run npm install"
+  exit 1
+fi
+
+##################
+# Copy the files #
+##################
 cp docs/_sidebar.md docs/SUMMARY.md
+
+#######################
+# Load the error code #
+#######################
+ERROR_CODE=$?
+
+##############################
+# Check the shell for errors #
+##############################
+if [ $ERROR_CODE -ne 0 ]; then
+  echo "ERROR! Failed to run cp"
+  exit 1
+fi
+
+###################
+# Run the gitbook #
+###################
 gitbook pdf docs/ docs/book.pdf
+
+#######################
+# Load the error code #
+#######################
+ERROR_CODE=$?
+
+##############################
+# Check the shell for errors #
+##############################
+if [ $ERROR_CODE -ne 0 ]; then
+  echo "ERROR! Failed to run gitbook"
+  exit 1
+fi
+
+####################
+# Remove dead file #
+####################
 rm docs/SUMMARY.md
 
+#######################
+# Load the error code #
+#######################
+ERROR_CODE=$?
+
+##############################
+# Check the shell for errors #
+##############################
+if [ $ERROR_CODE -ne 0 ]; then
+  echo "ERROR! Failed to run rm"
+  exit 1
+fi
+
+##########
+# Footer #
+##########
 echo "Your PDF is at docs/book.pdf. Commit it to your repo if you'd like to."
diff --git a/script/remove-repo b/script/remove-repo
--- a/script/remove-repo
+++ b/script/remove-repo
@@ -1,13 +1,47 @@
-#!/bin/sh
+#!/bin/bash
+################################################################################
+############################## Remove Repo #####################################
+################################################################################
 
-#you must have a githubteacher token
-#saved to your ENV variables in order to use this script
-reponame=$1
+###########################################################
+# You must have a githubteacher token                     #
+# saved to your ENV variables in order to use this script #
+###########################################################
+
+###########
+# GLOBALS #
+###########
+REPO_NAME=$1
 
 #set -x
 
-function deleteit () {
-  curl -s -i -H "Authorization: token $TEACHER_PAT" -X DELETE https://$INSTANCE_URL/repos/$CLASS_ORG/$reponame >> log.out 2>&1
-}
+################################################################################
+########################## Functions Below #####################################
+################################################################################
+################################################################################
+#### Function DeleteIt #########################################################
+function DeleteIt ()
+{
+  curl -s -i -H "Authorization: token $TEACHER_PAT" -X DELETE "https://$INSTANCE_URL/repos/$CLASS_ORG/$REPO_NAME" >> log.out 2>&1
 
-deleteit
+  #######################
+  # Load the error code #
+  #######################
+  ERROR_CODE=$?
+
+  ##############################
+  # Check the shell for errors #
+  ##############################
+  if [ $ERROR_CODE -ne 0 ]; then
+    echo "ERROR! Failed to Delete it!"
+    exit 1
+  fi
+}
+################################################################################
+############################### MAIN ###########################################
+################################################################################
+
+###################
+# Delete the repo #
+###################
+DeleteIt
diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -1,1 +1,23 @@
+#!/bin/bash
+
+################################################################################
+########################## Docsify them documents ##############################
+################################################################################
+
+###############
+# Run command #
+###############
 docsify serve docs
+
+#######################
+# Load the error code #
+#######################
+ERROR_CODE=$?
+
+##############################
+# Check the shell for errors #
+##############################
+if [ $ERROR_CODE -ne 0 ]; then
+  echo "ERROR! Failed to create docs!"
+  exit 1
+fi
