adding sanity check

diff --git a/script/teach-class b/script/teach-class
--- a/script/teach-class
+++ b/script/teach-class
@@ -97,6 +97,11 @@ function DoTask ()
     ############################################
     COLLAB_REPO_WHITESPACE="$(echo -e "$COLLAB_REPO" | tr -d '[:space:]')"
     COLLAB_REPO=$COLLAB_REPO_WHITESPACE
+  else
+    ##########################################
+    # Validate we have env variables sourced #
+    ##########################################
+    Check_Env
   fi
 
   ###########
@@ -173,6 +178,36 @@ function DoTask ()
     # echo "9: Grade client"
     echo "running script/grade-client"
     script/grade-client
+  fi
+}
+################################################################################
+#### Function Check_Env ########################################################
+function Check_Env ()
+{
+  ###############################
+  # Check length of TEACHER_PAT #
+  ###############################
+  PAT_LENGTH=${#TEACHER_PAT}
+  if [ $PAT_LENGTH -ne 40 ]; then
+    echo "ERROR! TEACHER_PAT not loaded or not correct length!"
+    echo "Please validate the .trainingmanualrc file!"
+    exit 1
+  fi
+
+  ###############################
+  # Check we have a TOKEN_OWNER #
+  ###############################
+  if [ -z $TOKEN_OWNER ]; then
+    echo "ERROR! TOKEN_OWNER not loaded or not correct length!"
+    echo "Please validate the .trainingmanualrc file!"
+  fi
+
+  ################################
+  # Check we have a INSTANCE_URL #
+  ################################
+  if [ -z $INSTANCE_URL ]; then
+    echo "ERROR! INSTANCE_URL not loaded or not correct length!"
+    echo "Please validate the .trainingmanualrc file!"
   fi
 }
 ################################################################################
